---
name: Check for new usages of deprecated functionality

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/gradually-deprecated.yaml'
      - './scripts/run-gradually-deprecated.sh'
      - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ./.go-version
      - run: bash ./scripts/run-gradually-deprecated.sh
  save-artifacts-on-fail:
    if: ${{ needs.test.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml