---
name: TeamCity Config Test

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/teamcity-test.yaml'
      - '!.teamcity/components/generated/**'
      - '!.teamcity/target/**'
      - '.teamcity/**'

concurrency:
  group: 'tctest-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  teamcity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: make teamcity-test
