---
name: 32 Bit Build

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/thirty-two-bit.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'thirtytwo-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  compatibility-32bit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: GOARCH=386 GOOS=linux go build -o 32bitbuild .
  save-artifacts-on-fail:
    if: ${{ needs.compatibility-32bit-test.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
